SELECT DISTINCT 
       CATEGORIAN1 NIVEL_1, SEQCATEGORIAN1 CATEGORYREFERENCE,
       CATEGORIAN2 NIVEL_2, SEQCATEGORIAN2 CATEGORYREFERENCE,
       CATEGORIAN3 NIVEL_3, SEQCATEGORIAN3 CATEGORYREFERENCE,
       CATEGORIAN4 NIVEL_4, SEQCATEGORIAN4 CATEGORYREFERENCE,
       CATEGORIAN5 NIVEL_5, SEQCATEGORIAN5 CATEGORYREFERENCE,
       RTRIM(SEQCATEGORIAN1||'-'||SEQCATEGORIAN2||'-'||SEQCATEGORIAN3||'-'||SEQCATEGORIAN4||'-'||SEQCATEGORIAN5, '-') CHAVE,
       RTRIM(CATEGORIAN1||'-'||CATEGORIAN2||'-'||CATEGORIAN3||'-'||CATEGORIAN4||'-'||CATEGORIAN5,'-') CHAVE_DESCRICAO
       
  FROM DIM_CATEGORIA@CONSINCODW
  
  WHERE 1=1 
    ORDER BY 1,3,5,7,9
  -- SEQCATEGORIAN2 = 44117
