CREATE OR REPLACE VIEW NAGV_IEAP_MENORPROMOCATIVA AS 

SELECT T.SKU,
       T.STOREREFERENCE,
       T.DESCRIPTION,
       T.STARTDATETIME,
       T.ENDDATETIME,
       T.ISACTIVE,
       T.PRICE
       
FROM (
    SELECT T.*,
           ROW_NUMBER() OVER (PARTITION BY T.SKU, T.STOREREFERENCE ORDER BY T.PRICE ASC) ODR
      FROM NAGV_IEAP_PROMOCOES_ATIVAS T
) T

WHERE ODR = 1;
