CREATE OR REPLACE VIEW NAGV_IEAP_MENORPROMOCATIVA AS

SELECT PromocTodas.SKU,
       PromocTodas.STOREREFERENCE,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.DESCRIPTION   ELSE PromocTodas.DESCRIPTION   END DESCRIPTION,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.STARTDATETIME ELSE PromocTodas.STARTDATETIME END STARTDATETIME,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.ENDDATETIME   ELSE PromocTodas.ENDDATETIME   END ENDDATETIME,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.ISACTIVE      ELSE PromocTodas.ISACTIVE      END ISACTIVE,
       CASE WHEN PromocAtivas.ISACTIVE = 'TRUE' AND PromocTodas.ISACTIVE = 'INACTIVE' THEN PromocAtivas.PRICE         ELSE PromocTodas.PRICE         END PRICE

FROM (
    SELECT T.*,
           ROW_NUMBER() OVER (PARTITION BY T.SKU, T.STOREREFERENCE ORDER BY T.PRICE ASC) ODR1
      FROM NAGV_IEAP_PROMOCOES_ATIVAS T
) PromocTodas 

LEFT JOIN

(
    SELECT T.*,
           ROW_NUMBER() OVER (PARTITION BY T.SKU, T.STOREREFERENCE ORDER BY T.PRICE ASC) ODR2
      FROM NAGV_IEAP_PROMOCOES_ATIVAS_ST T
) PromocAtivas ON PromocTodas.SKU = PromocAtivas.SKU AND PromocTodas.STOREREFERENCE = PromocAtivas.STOREREFERENCE AND ODR2 = 1

WHERE ODR1 = 1
