CREATE OR REPLACE VIEW NAGV_LIMITE_QTD_BLACK AS

SELECT SEQFAMILIA, CATEGORIAN1, CATEGORIAN2, CATEGORIAN3,
       CASE 
         WHEN CATEGORIAN1 = 'AÇOUGUE' THEN 20
         WHEN CATEGORIAN1 = 'HORTIFRUTI' THEN 20
         WHEN CATEGORIAN1 = 'BASICOS E MATINAIS' AND CATEGORIAN3 IN ('ACUCAR','AZEITE','CAFE','CESTA BASICA','CREME DE LEITE','LEITE CONDENSADO') THEN 20
         WHEN CATEGORIAN1 = 'FRIOS E LATICINIOS' AND CATEGORIAN3 IN ('QUEIJOS','QUEIJO RALADO','EMBUTIDOS E DEFUMADOS','MARGARINA','MANTEIRA') THEN 20
         WHEN CATEGORIAN1 = 'FRIOS E LATICINIOS' AND CATEGORIAN3 = 'AVES NATALINAS' THEN 50
         WHEN CATEGORIAN1 = 'BEBIDAS' AND CATEGORIAN3 = 'CERVEJA' THEN 50
         WHEN CATEGORIAN1 = 'LIMPEZA' AND CATEGORIAN3 IN ('AGUA SANITARIA','DESIFETANTE') THEN 20
         WHEN CATEGORIAN1 = 'COMMODITIES' THEN 20
           ELSE NULL END
       MAXQTD
  FROM ETLV_CATEGORIA
 WHERE CATEGORIAN1 = 'BEBIDAS';
