CREATE OR REPLACE VIEW NAGV_IEAP_CATALOGO_ALTERADOS AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       X.SEQPRODUTO PRODUCT_SKU,
       X.NROEMPRESA STORE_REFERENCE,
       LISTAGG(SEQCATEGORIAN1||CASE WHEN SEQCATEGORIAN2 IS NOT NULL THEN ', '||SEQCATEGORIAN2 END
                             ||CASE WHEN SEQCATEGORIAN3 IS NOT NULL THEN ', '||SEQCATEGORIAN3 END)
       WITHIN GROUP (ORDER BY C.SEQFAMILIA, SEQCATEGORIAN1, SEQCATEGORIAN2, SEQCATEGORIAN3) CATEGORY_REFERENCE,
       S.PRECOBASENORMAL PRICE,
       X.ESTQLOJA STOCK,
       NULL MAXQTD,
       NULL MINQTD,
       CASE WHEN S.STATUSVENDA = 'A' AND P.INDINTEGRAECOMMERCE = 'S' THEN 'TRUE' ELSE 'FALSE' END ISACTIVE,
       COALESCE(CATEGORIAN1, CATEGORIAN2, CATEGORIAN3) LOCATION,
       NULL SECURITYSTOCK,
       NULL TAGS

  FROM MRL_PRODUTOEMPRESA X INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = X.NROEMPRESA
                            INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = X.SEQPRODUTO AND S.NROSEGMENTO = M.NROSEGMENTOPRINC AND S.NROEMPRESA = X.NROEMPRESA
                            INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = X.SEQPRODUTO
                            INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = P.SEQFAMILIA
WHERE 1=1
  AND X.NROEMPRESA < 300
  AND S.QTDEMBALAGEM = 1
  AND S.DTAVALIDACAOPRECO >= TRUNC(SYSDATE)
  AND S.PRECOVALIDPROMOC = 0
  AND P.INDINTEGRAECOMMERCE = 'S'
  AND S.STATUSVENDA = 'A'

GROUP BY X.SEQPRODUTO, X.NROEMPRESA, S.PRECOBASENORMAL, X.ESTQLOJA,
         CASE WHEN S.STATUSVENDA = 'A' AND P.INDINTEGRAECOMMERCE = 'S' THEN 'TRUE' ELSE 'FALSE' END,
         COALESCE(CATEGORIAN1, CATEGORIAN2, CATEGORIAN3);
